LP:1990014 fix debug middleware
When response jas no `content` attribute, default value will be
returned.

Default value should be of type `bytes`, not `str`, otherwise it will
fail to decode with an exception:

```
AttributeError: 'str' object has no attribute 'decode'.
```

From Django documentation:
  HttpResponse.content
  A bytestring representing the content, encoded from a string if necessary.

(cherry picked from commit e9587d9158ba3e4cfe8681413e7ce85ce16027af)