fix: add missing pkg_resources dependency (#451)
The `3.4/edge` snap was unavailable due to:

File "/snap/maas/42249/usr/lib/python3/dist-packages/zope/__init__.py", line 1, in <module>
__import__('pkg_resources').declare_namespace(__name__)
ModuleNotFoundError: No module named 'pkg_resources'

This PR adds `python3-pkg-resources` to stage-packages in snapcraft.yaml
which fixes the issue.

Signed-off-by: Leah Goldberg <leah.goldberg@canonical.com>