fix: set explicit testtools version
testtools 2.6.0 has a breaking change [1] that leads to an error:

    AttributeError: module 'email' has no attribute 'message'

[1]: https://github.com/testing-cabal/testtools/commit/b4bcd3c3d1964352d5f51def08629114057541a8

(cherry picked from commit f08e136c52d5dab55e73da9f9e65042bb28ad612)