Bug #2066276: ipv6 test failures: AttributeError: 'RRHeader' object has no attribute '_address'
fix: parse DNS results correctly

(cherry picked from commit 4f6ef7d4e2feab5445b39330949ed5a13d10d526)